name: Grupo de Usuários Crossmobile do Brasil
markdown: redcarpet
highlighter: pygments
destination: public_html

gems:
  - bootstrap-sass
  - jekyll-assets
  # - jekyll-assets/bootstrap
  # - jekyll-assets/font-awesome

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

assets:
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
